# This workflow bumps the 'build' version based on the contents of the VERSION file.
# The VERSION file should be in the format of 'X.X.X--Y' - the 'Y' is incremented and
# pushed back to the VERSION file.
#
# For example, if the contents of VERSION were '2.1.1--1', after this runs the contents
# will be '2.1.1--2'.
#
# Then, the Dockerfile is built and pushed to Docker Hub. Three tags are pushed as well:
# One for the software version (2.1.1), one for the full version (2.1.1--2), and one for latest.

name: CI

# Triggers the workflow on push events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  bump:
    # Do not run if "[skip-ci]" is in the commit message.
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get versions from files in repo, update them, and set in env
      run: |
        software_version=$(cat SOFTWARE_VERSION)
        version=$(cat VERSION)
        arrIN=(${version//--/ }) # split the versions on the '+'
        new_base_version=$(echo ${arrIN[1]} + 1 | bc)
        export new_version="${software_version}--${new_base_version}"
        echo "::set-env name=NEW_VERSION::$new_version"
        echo "::set-env name=SOFTWARE_VERSION::$software_version"
    - name: Bump version
      run: |
        echo "${{ env.NEW_VERSION }}" > VERSION
        git config --global user.name 'Kenneth Daily'
        git config --global user.email 'kdaily@users.noreply.github.com'
        git commit -am "Bump version to ${{ env.NEW_VERSION }}"
        git push
        echo "Bump version to ${{ env.NEW_VERSION }}"
        
  build:
    runs-on: ubuntu-latest
    needs: bump

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Get versions from files in repo and set in env
      run: |
        software_version=$(cat SOFTWARE_VERSION)
        version=$(cat VERSION)
        echo "::set-env name=NEW_VERSION::$version"
        echo "::set-env name=SOFTWARE_VERSION::$software_version"
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: sagebionetworks/${{ github.event.repository.name }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "${{ env.NEW_VERSION }},${{ env.SOFTWARE_VERSION }},latest"
